##
## EPITECH PROJECT, 2020
## makefile
## File description:
## make Makefile
##

#SRC = $(#wildcard *.c)


ALL:
	cd lib/my && make
	gcc -o put_rmn_nbr *.c -L lib/my/ -lmy -I./include -Wall -Wextra

clean:
	rm -rf *.o

.PHONY: clean
