##
## EPITECH PROJECT, 2020
## Solo_Stumper
## File description:
## Makefile
##

SRC =	ss5.c \
		my_del_mult_space.c

NAME = rostring

NAME_TEST = unit_tests

all:
	gcc -o $(NAME) $(SRC)

clean:
	rm -rf *~

fclean: clean
	rm -rf  $(NAME)

re: fclean all

.PHONY: all clean fclean re tests_run