##
## EPITECH PROJECT, 2020
## Solo_Stumper
## File description:
## Makefile
##

SRC = ss1.c

NAME = clean_str

all:
	gcc -o $(NAME) $(SRC)

clean:
	rm -rf *~

fclean: clean
	rm -rf  $(NAME)

re: fclean all

.PHONY: all clean fclean re